amplitude_scale_range: 0.5,1.5
batch_size: 1024
cluster_method: MS
detect_chunk_size: 3000000
detect_method: model
dmodel_arch: transformer
dmodel_save_path: simsort_pretrained/detector_bbp_L1-L5-8192/saved_models
down_dim_method: UMAP
dropout: 0.0
e_batch_class: 10
e_batch_size: 256
e_dropout: 0.1
e_hidden_size: 512
e_input_size: 4
e_learning_rate: 0.001
e_max_channels: 4
e_nhead: 4
e_noise_level: 4.0
e_num_epochs: 50
e_num_layers: 1
e_probabilities: 1,0,1,1
e_rl: 0
e_rl_batches: 5
e_rl_weight: 0.1
e_scale_range: 0,1
e_shift_max: 50
e_strech_range: 0.5
e_transform_prob: 0.5
emodel_arch: gru
emodel_save_path: simsort_pretrained/extractor_bbp_L1-L5-8192/saved_models
eps: 0.15
exclude_index: 0
hidden_size: 256
input_size: 4
learning_rate: 0.001
lfp_input_points: 2000
loo_exp: 0
min_samples: 20
model_threshold: 0.97
nhead: 4
noise_level: 0.6
num_epochs: 200
num_layers: 1
only_test: 1
output_size: 1
pos_weight: 1.0
predict_cycle: 20
probabilities: 1,1,1
quantile: 0.04
resume: false
seed: 42
si_sorter: kilosort
sorting_chunk_size: 3000000
task_name: sorting
test_dataset_type: hybrid
threshold: 6.0
time_jitter_range: 5
train_dataset_type: bbp
transform_prob: 0.5
tsne_seed: 42
use_true_clusters: 0
use_true_snippets: 0
weight_decay: 1.0e-05
